'use strict';

// ###########################
// DO NOT EDIT THIS FILE !!!!!
// ###########################

$(function() {

  var deli = [];

  $( "#take-number" ).click(function() {
    var name = $("#name").val();
    $("#name").val('');
    var response = takeANumber(deli, name);
    $('#in-line').text(response);
  });

  $('#check-line').click(function() {
    $('#line').text(line(deli));
  });

  $('#serve').click(function() {
    $('#served').text(nowServing(deli));
  });
});
